### ISSUE TITLE
Get add-on verified by Mozilla

### ISSUE THREAD

**Issue by gurdas** [corajr/zotero-prevent-duplicates#5]
Starting with Firefox 43, add-ons will need to be signed/verified to continue to work. The "zotero-prevent-duplicates" add-on shows up as not verified in Firefox add-ons page. This issue is discussed here:
https://forums.zotero.org/discussion/52608/future-direction-of-zotero-firefox-addon/

Can the owner/author please get this add-on verified by Mozilla?

**Comment by rcoreilly** [comment]
I guess this won't happen by now but trying another vote! :)
